Repository x73495/mailru-android-course-project, pull requests merged in 2021-11, with the labels that each got.

#35 Добавить иконку "Изменить"
  app/src/main/res/drawable/ic_edit.xml
Labels: invalid

#39 Реструктуризация папок, добавление вью моделей
  app/src/main/java/company/vk/education/androidcourse/rememberthepills/course/view/FragmentCourse.kt
  app/src/main/java/company/vk/education/androidcourse/rememberthepills/course/viewModel/CourseViewModel.kt
  app/src/main/java/company/vk/education/androidcourse/rememberthepills/courseHistory/view/FragmentCourseHistory.kt
  app/src/main/java/company/vk/education/androidcourse/rememberthepills/courseHistory/viewModel/CourseHistoryViewModel.kt
  app/src/main/java/company/vk/education/androidcourse/rememberthepills/drug/view/FragmentDrug.kt
  app/src/main/java/company/vk/education/androidcourse/rememberthepills/drug/viewModel/DrugViewModel.kt
  app/src/main/java/company/vk/education/androidcourse/rememberthepills/drugList/model/DrugEntry.kt
  app/src/main/java/company/vk/education/androidcourse/rememberthepills/drugList/view/FragmentDrugList.kt
  app/src/main/java/company/vk/education/androidcourse/rememberthepills/drugList/view/adapter/DrugListAdapter.kt
  app/src/main/java/company/vk/education/androidcourse/rememberthepills/drugList/viewModel/DrugListViewModel.kt
  app/src/main/java/company/vk/education/androidcourse/rememberthepills/profile/view/FragmentProfile.kt
  app/src/main/java/company/vk/education/androidcourse/rememberthepills/profile/viewModel/ProfileViewModel.kt
  app/src/main/java/company/vk/education/androidcourse/rememberthepills/schedule/model/CourseEntry.kt
  app/src/main/java/company/vk/education/androidcourse/rememberthepills/schedule/view/FragmentSchedule.kt
  app/src/main/java/company/vk/education/androidcourse/rememberthepills/schedule/view/adapter/CourseListAdapter.kt
  app/src/main/java/company/vk/education/androidcourse/rememberthepills/schedule/viewModel/ScheduleViewModel.kt
  app/src/main/res/drawable/border_course_entry.xml
  app/src/main/res/layout/fragment_course.xml
  app/src/main/res/layout/view_course_entry.xml
  app/src/main/res/layout/view_drug_entry.xml
  app/src/main/res/navigation/default_navigation.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: enhancement

#46 Фикс ненужного фокуса на EditText при добавлении времени приёма
  app/src/main/res/layout/fragment_course.xml
Labels: bug
